### ISSUE TITLE
Integración con Twitter

### ISSUE THREAD

**Issue by UlisesGascon** [memezinga/memezinga#7]
### Pendiente
- [ ] Generar las credenciales de prueba para development
- [ ] Generar las credenciales de la cuenta oficial de memezinga (@UlisesGascon )
- [ ] Integrar Twitter api con Nodejs
- [ ] Disparar tweets con las nuevas imagenes que lleguen a Firebase, ver #6 
- [ ] Disparar tweets de #12
- [ ] Disparar tweets de los más votados, según #11
